//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : StdOutLogger.java
//  @ Date : 19/10/2019
//  @ Author : 
//
//




public class StdOutLogger implements Observer {
	
	public void report(Observable observable) {
		System.out.println(observable);
	}
}
