import java.io.FileNotFoundException;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Application.java
//  @ Date : 19/10/2019
//  @ Author : 
//
//




public class Application {
	public static void main(String[] args) throws FileNotFoundException {
		PercentCounter pc = new PercentCounter();
		StdOutLogger sol = new StdOutLogger();
		FileLogger fl = new FileLogger("observer.txt");
		pc.register(sol);
		pc.register(fl);
		pc.run();
		
	}
}
