//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Observer.java
//  @ Date : 19/10/2019
//  @ Author : 
//
//




public class Observer {
	public void report(Observable observable) {
		
	}
}
